server:
  port: 8077
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g130table
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml